return {
	"m4xshen/hardtime.nvim",
	enabled = false,
	init = function()
		vim.opt.showmode = false
	end,
	dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
	opts = {
		restriction_mode = "hint",
		disabled_filetypes = {
			"NvimTree",
			"TelescopePrompt",
			"aerial",
			"alpha",
			"checkhealth",
			"dapui-repl",
			"dapui_breakpoints",
			"dapui_console",
			"dapui_scopes",
			"dapui_stacks",
			"dapui_watches",
			"DressingInput",
			"DressingSelect",
			"help",
			"lazy",
			"mason",
			"neo-tree",
			"neo-tree-popup",
			"netrw",
			"noice",
			"notify",
			"prompt",
			"qf",
			"harpoon",
			"fugitive",
			"nofile",
			"prompt",
			"terminal",
		},
	},
}
